// build.rs — Generate a flat list of all built-in unit types from per-dimension
// inventory macros.  The generated `all_builtin_unit_types!($cb)` macro is
// consumed by `unit_arithmetic.rs` so that `register_builtin_units!` is driven
// from the canonical inventories rather than a hand-maintained flat list.

use std::fs;
use std::path::Path;

/// One inventory macro to extract.
struct Inventory {
    /// Macro name to look for, e.g. `angular_units`.
    macro_name: &'static str,
    /// Source file relative to `src/units/`.
    file: &'static str,
    /// Fully qualified module prefix used in `crate::…` paths.
    module_prefix: &'static str,
}

const INVENTORIES: &[Inventory] = &[
    Inventory {
        macro_name: "angular_units",
        file: "angular.rs",
        module_prefix: "crate::units::angular",
    },
    Inventory {
        macro_name: "length_units",
        file: "length.rs",
        module_prefix: "crate::units::length",
    },
    Inventory {
        macro_name: "length_nominal_units",
        file: "length.rs",
        module_prefix: "crate::units::length::nominal",
    },
    Inventory {
        macro_name: "time_units",
        file: "time.rs",
        module_prefix: "crate::units::time",
    },
    Inventory {
        macro_name: "mass_units",
        file: "mass.rs",
        module_prefix: "crate::units::mass",
    },
    Inventory {
        macro_name: "power_units",
        file: "power.rs",
        module_prefix: "crate::units::power",
    },
    Inventory {
        macro_name: "area_units",
        file: "area.rs",
        module_prefix: "crate::units::area",
    },
    Inventory {
        macro_name: "volume_units",
        file: "volume.rs",
        module_prefix: "crate::units::volume",
    },
];

fn main() {
    let units_dir = Path::new("src/units");
    println!("cargo::rerun-if-changed=src/units/");

    let mut all_units: Vec<String> = Vec::new();

    // Unitless is not in any dimension inventory — add it explicitly.
    all_units.push("crate::unit::Unitless".to_string());

    for inv in INVENTORIES {
        let path = units_dir.join(inv.file);
        let src = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

        let types = extract_inventory_types(&src, inv.macro_name)
            .unwrap_or_else(|| panic!("could not find macro `{}` in {}", inv.macro_name, inv.file));

        for ty in types {
            all_units.push(format!("{}::{}", inv.module_prefix, ty));
        }
    }

    // Write the generated macro.
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("all_builtin_units.rs");

    let mut buf = String::new();
    buf.push_str(
        "// Auto-generated by build.rs from per-dimension inventory macros.\n\
         // Do not edit manually.\n\n\
         macro_rules! all_builtin_unit_types {\n\
         \x20   ($cb:ident) => {\n\
         \x20       $cb!(\n",
    );
    for (i, unit) in all_units.iter().enumerate() {
        buf.push_str("            ");
        buf.push_str(unit);
        if i + 1 < all_units.len() {
            buf.push(',');
        }
        buf.push('\n');
    }
    buf.push_str(
        "        );\n\
         \x20   };\n\
         }\n",
    );

    fs::write(&out_path, buf)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

/// Extract the list of unit type identifiers from a `$name!` inventory macro.
///
/// Looks for:
/// ```text
/// macro_rules! $name {
///     ($cb:path) => {
///         $cb!(
///             Type1,
///             Type2,
///             ...
///         );
///     };
/// }
/// ```
///
/// Returns the list of identifiers inside the `$cb!(...)` call.
fn extract_inventory_types(source: &str, macro_name: &str) -> Option<Vec<String>> {
    // Find the macro_rules! declaration.
    let marker = format!("macro_rules! {macro_name}");
    let macro_start = source.find(&marker)?;
    let after_marker = &source[macro_start + marker.len()..];

    // Find the `$cb!(` invocation inside the macro body.
    let cb_marker = "$cb!(";
    let cb_pos = after_marker.find(cb_marker)?;
    let after_cb = &after_marker[cb_pos + cb_marker.len()..];

    // Find the matching closing `)`.  We track nesting depth because some
    // ratios in unit attributes contain parentheses, but those are outside
    // the macro body we're parsing here (the inventory macros only list bare
    // identifiers).
    let mut depth: u32 = 1;
    let mut end = None;
    for (i, ch) in after_cb.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    end = Some(i);
                    break;
                }
            }
            _ => {}
        }
    }
    let end = end?;
    let body = &after_cb[..end];

    // Split on commas and collect non-empty trimmed identifiers.
    let types: Vec<String> = body
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();

    Some(types)
}
