// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! Trait implementations for downstream crate integration.
//!
//! This module provides pre-implemented conversions between `qtty` types and [`QttyQuantity`],
//! making it easy for downstream Rust crates to integrate with the FFI layer.
//!
//! # Auto-generated conversions
//!
//! `From`/`TryFrom` implementations are auto-generated at build time from
//! `discriminants.csv` + qtty-core's inventory macros for all units that have
//! a corresponding Rust type. This covers all units in the registry.
//!
//! Additional unit conversions can be implemented in downstream crates using the
//! [`impl_unit_ffi!`] macro.
//!
//! # Usage
//!
//! ## Converting to FFI format
//!
//! ```rust
//! use qtty::length::Meters;
//! use qtty_ffi::QttyQuantity;
//!
//! let meters = Meters::new(1000.0);
//! let ffi_qty: QttyQuantity = meters.into();
//! ```
//!
//! ## Converting from FFI format
//!
//! ```rust
//! use qtty::length::Kilometers;
//! use qtty_ffi::{QttyQuantity, UnitId};
//!
//! // A quantity received from FFI (could be in any compatible unit)
//! let ffi_qty = QttyQuantity::new(1000.0, UnitId::Meter);
//!
//! // Convert to Kilometers (automatic unit conversion happens)
//! let km: Kilometers = ffi_qty.try_into().unwrap();
//! assert!((km.value() - 1.0).abs() < 1e-12);
//! ```
//!
//! ## Error handling
//!
//! Conversion from [`QttyQuantity`] can fail if the dimensions are incompatible:
//!
//! ```rust
//! use qtty::length::Meters;
//! use qtty_ffi::{QttyQuantity, UnitId};
//!
//! let time_qty = QttyQuantity::new(60.0, UnitId::Second);
//! let result: Result<Meters, i32> = time_qty.try_into();
//! assert!(result.is_err());
//! ```

// Auto-generated From/TryFrom impls for all units.
// Generated by build.rs from discriminants.csv + qtty-core inventories.
include!(concat!(env!("OUT_DIR"), "/unit_conversions.rs"));

#[cfg(test)]
mod tests {
    use crate::QttyQuantity;
    use crate::QttyStatus;
    use crate::UnitId;
    use approx::assert_relative_eq;
    use core::f64::consts::PI;

    #[test]
    fn test_meters_roundtrip() {
        let original = qtty::length::Meters::new(42.5);
        let ffi: QttyQuantity = original.into();
        let back: qtty::length::Meters = ffi.try_into().unwrap();
        assert_relative_eq!(back.value(), 42.5, epsilon = 1e-12);
    }

    #[test]
    fn test_kilometers_roundtrip() {
        let original = qtty::length::Kilometers::new(1.5);
        let ffi: QttyQuantity = original.into();
        let back: qtty::length::Kilometers = ffi.try_into().unwrap();
        assert_relative_eq!(back.value(), 1.5, epsilon = 1e-12);
    }

    #[test]
    fn test_meters_to_kilometers_via_ffi() {
        let meters = qtty::length::Meters::new(1000.0);
        let ffi: QttyQuantity = meters.into();
        let km: qtty::length::Kilometers = ffi.try_into().unwrap();
        assert_relative_eq!(km.value(), 1.0, epsilon = 1e-12);
    }

    #[test]
    fn test_seconds_roundtrip() {
        let original = qtty::time::Seconds::new(3600.0);
        let ffi: QttyQuantity = original.into();
        let back: qtty::time::Seconds = ffi.try_into().unwrap();
        assert_relative_eq!(back.value(), 3600.0, epsilon = 1e-12);
    }

    #[test]
    fn test_hours_to_seconds_via_ffi() {
        let hours = qtty::time::Hours::new(1.0);
        let ffi: QttyQuantity = hours.into();
        let secs: qtty::time::Seconds = ffi.try_into().unwrap();
        assert_relative_eq!(secs.value(), 3600.0, epsilon = 1e-12);
    }

    #[test]
    fn test_degrees_to_radians_via_ffi() {
        let degrees = qtty::angular::Degrees::new(180.0);
        let ffi: QttyQuantity = degrees.into();
        let radians: qtty::angular::Radians = ffi.try_into().unwrap();
        assert_relative_eq!(radians.value(), PI, epsilon = 1e-12);
    }

    #[test]
    fn test_incompatible_conversion_fails() {
        let meters = qtty::length::Meters::new(100.0);
        let ffi: QttyQuantity = meters.into();
        let result: Result<qtty::time::Seconds, i32> = ffi.try_into();
        assert_eq!(result, Err(QttyStatus::IncompatibleDim as i32));
    }

    #[test]
    fn test_from_into_all_common_units() {
        use qtty::angular::{Degrees, Radians};
        use qtty::length::{Kilometers, Meters};
        use qtty::time::{Days, Hours, Minutes, Seconds};

        let meters_qty: QttyQuantity = Meters::new(12.0).into();
        assert_eq!(meters_qty.unit, UnitId::Meter as u32);
        assert_relative_eq!(meters_qty.value, 12.0, epsilon = 1e-12);

        let km_qty: QttyQuantity = Kilometers::new(3.0).into();
        assert_eq!(km_qty.unit, UnitId::Kilometer as u32);
        assert_relative_eq!(km_qty.value, 3.0, epsilon = 1e-12);

        let m_from_km: Meters = km_qty.try_into().unwrap();
        assert_relative_eq!(m_from_km.value(), 3000.0, epsilon = 1e-12);

        let km_from_m: Kilometers = meters_qty.try_into().unwrap();
        assert_relative_eq!(km_from_m.value(), 0.012, epsilon = 1e-12);

        let s_qty: QttyQuantity = Seconds::new(90.0).into();
        assert_eq!(s_qty.unit, UnitId::Second as u32);

        let min_qty: QttyQuantity = Minutes::new(2.5).into();
        assert_eq!(min_qty.unit, UnitId::Minute as u32);

        let s_from_min: Seconds = min_qty.try_into().unwrap();
        assert_relative_eq!(s_from_min.value(), 150.0, epsilon = 1e-12);

        let h_qty: QttyQuantity = Hours::new(4.0).into();
        assert_eq!(h_qty.unit, UnitId::Hour as u32);

        let d_qty: QttyQuantity = Days::new(1.25).into();
        assert_eq!(d_qty.unit, UnitId::Day as u32);

        let rad_qty: QttyQuantity = Radians::new(PI).into();
        assert_eq!(rad_qty.unit, UnitId::Radian as u32);

        let deg_qty: QttyQuantity = Degrees::new(270.0).into();
        assert_eq!(deg_qty.unit, UnitId::Degree as u32);

        let rad_from_deg: Radians = deg_qty.try_into().unwrap();
        assert_relative_eq!(rad_from_deg.value(), 1.5 * PI, epsilon = 1e-12);

        let deg_from_rad: Degrees = rad_qty.try_into().unwrap();
        assert_relative_eq!(deg_from_rad.value(), 180.0, epsilon = 1e-12);
    }

    #[test]
    fn test_area_roundtrip() {
        let original = qtty::area::SquareMeters::new(1_000_000.0);
        let ffi: QttyQuantity = original.into();
        let back: qtty::area::SquareKilometers = ffi.try_into().unwrap();
        assert_relative_eq!(back.value(), 1.0, epsilon = 1e-6);
    }

    #[test]
    fn test_volume_roundtrip() {
        let original = qtty::volume::Liters::new(1000.0);
        let ffi: QttyQuantity = original.into();
        let back: qtty::volume::CubicMeters = ffi.try_into().unwrap();
        assert_relative_eq!(back.value(), 1.0, epsilon = 1e-12);
    }
}
