// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! C-compatible FFI bindings for `qtty`.
//!
//! `qtty-ffi` exposes a stable ABI around `qtty`'s unit registry and
//! conversion logic. It is intended for C and C++ adapters, and for Rust
//! crates that need to mirror `qtty` quantities across an FFI boundary.
//!
//! # What this crate provides
//!
//! - ABI-stable carrier structs such as [`QttyQuantity`] and
//!   [`QttyDerivedQuantity`]
//! - stable [`UnitId`] and [`DimensionId`] discriminants
//! - `extern "C"` functions for construction, conversion, validation, and
//!   formatting
//! - a generated public header at `include/qtty_ffi.h`
//! - optional Rust-side `qtty_serde` and `pyo3` helpers
//!
//! # Quick Start (C/C++)
//!
//! ```c
//! #include "qtty_ffi.h"
//!
//! qtty_quantity_t meters;
//! qtty_quantity_make(1000.0, UNIT_ID_METER, &meters);
//!
//! qtty_quantity_t kilometers;
//! if (qtty_quantity_convert(meters, UNIT_ID_KILOMETER, &kilometers) == QTTY_OK) {
//!     /* kilometers.value == 1.0 */
//! }
//! ```
//!
//! # Quick Start (Rust)
//!
//! ```rust
//! use qtty::Meter;
//! use qtty_ffi::{QttyQuantity, UnitId};
//!
//! let qty: QttyQuantity = Meter::new(12.5).into();
//! assert_eq!(qty.unit, UnitId::Meter as u32);
//! ```
//!
//! # ABI Stability
//!
//! Existing [`UnitId`] and [`DimensionId`] values, carrier layouts, status
//! codes, and exported function signatures are part of the ABI contract.
//! New units or functions may be added in future releases, but existing values
//! remain stable.
//!
//! # Error Handling
//!
//! All FFI functions return status codes:
//!
//! - [`QttyStatus::Ok`] (0): Success
//! - [`QttyStatus::UnknownUnit`] (-1): Invalid unit ID
//! - [`QttyStatus::IncompatibleDim`] (-2): Dimension mismatch
//! - [`QttyStatus::NullOut`] (-3): Null output pointer
//! - [`QttyStatus::BufferTooSmall`] (-4): Output buffer too small
//! - [`QttyStatus::InternalPanic`] (-5): Rust panic caught at the FFI boundary
//!
//! Format flags for [`qtty_quantity_format`]:
//!
//! - [`QTTY_FMT_DEFAULT`] (0): decimal notation
//! - [`QTTY_FMT_LOWER_EXP`] (1): scientific notation (lowercase `e`)
//! - [`QTTY_FMT_UPPER_EXP`] (2): scientific notation (uppercase `E`)
//!
//! # Thread Safety
//!
//! All functions are thread-safe. The library contains no global mutable state.

#![deny(missing_docs)]
// PyO3 generated code contains unsafe operations, so we can't enforce this when pyo3 feature is enabled
#![cfg_attr(not(feature = "pyo3"), deny(unsafe_op_in_unsafe_fn))]

// Core modules
mod ffi;
pub mod helpers;
#[macro_use]
pub mod macros;
pub mod registry;
mod types;

// Re-export FFI functions
pub use ffi::{
    qtty_derived_convert, qtty_derived_make, qtty_ffi_version, qtty_quantity_convert,
    qtty_quantity_convert_value, qtty_quantity_format, qtty_quantity_make, qtty_unit_dimension,
    qtty_unit_is_valid, qtty_unit_name, qtty_units_compatible,
};

// Named unit ID constants for C caller ergonomics — each is the u32 discriminant
// of the corresponding UnitId variant.  These are stable ABI values.
// Auto-generated by build.rs from discriminants.csv + qtty-core inventories.
include!(concat!(env!("OUT_DIR"), "/unit_constants.rs"));

// Re-export types
pub use types::{
    DimensionId, QttyDerivedQuantity, QttyQuantity, QttyStatus, UnitId, QTTY_FMT_DEFAULT,
    QTTY_FMT_LOWER_EXP, QTTY_FMT_UPPER_EXP,
};

// The impl_unit_ffi! macro is automatically exported at crate root by #[macro_export]

#[cfg(test)]
mod tests {
    use super::*;
    use core::mem::{align_of, size_of};

    #[test]
    fn test_qtty_quantity_layout() {
        assert_eq!(size_of::<QttyQuantity>(), 16);
        assert_eq!(align_of::<QttyQuantity>(), 8);
    }

    #[test]
    fn test_unit_id_layout() {
        assert_eq!(size_of::<UnitId>(), 4);
        assert_eq!(align_of::<UnitId>(), 4);
    }

    #[test]
    fn test_dimension_id_layout() {
        assert_eq!(size_of::<DimensionId>(), 4);
        assert_eq!(align_of::<DimensionId>(), 4);
    }

    #[test]
    fn test_qtty_status_layout() {
        assert_eq!(size_of::<QttyStatus>(), 4);
        assert_eq!(align_of::<QttyStatus>(), 4);
    }

    #[test]
    fn test_known_conversion_meters_to_kilometers() {
        let mut out = QttyQuantity::default();
        let src = QttyQuantity::new(1000.0, UnitId::Meter);
        let status = unsafe { qtty_quantity_convert(src, UnitId::Kilometer as u32, &mut out) };
        assert_eq!(status, QttyStatus::Ok);
        assert!((out.value - 1.0).abs() < 1e-12);
        assert_eq!(out.unit, UnitId::Kilometer as u32);
    }

    #[test]
    fn test_known_conversion_seconds_to_hours() {
        let mut out = QttyQuantity::default();
        let src = QttyQuantity::new(3600.0, UnitId::Second);
        let status = unsafe { qtty_quantity_convert(src, UnitId::Hour as u32, &mut out) };
        assert_eq!(status, QttyStatus::Ok);
        assert!((out.value - 1.0).abs() < 1e-12);
        assert_eq!(out.unit, UnitId::Hour as u32);
    }

    #[test]
    fn test_known_conversion_degrees_to_radians() {
        use core::f64::consts::PI;
        let mut out = QttyQuantity::default();
        let src = QttyQuantity::new(180.0, UnitId::Degree);
        let status = unsafe { qtty_quantity_convert(src, UnitId::Radian as u32, &mut out) };
        assert_eq!(status, QttyStatus::Ok);
        assert!((out.value - PI).abs() < 1e-12);
        assert_eq!(out.unit, UnitId::Radian as u32);
    }

    #[test]
    fn test_incompatible_conversion_fails() {
        let mut out = QttyQuantity::default();
        let src = QttyQuantity::new(100.0, UnitId::Meter);
        let status = unsafe { qtty_quantity_convert(src, UnitId::Second as u32, &mut out) };
        assert_eq!(status, QttyStatus::IncompatibleDim);
    }

    #[test]
    fn test_null_out_pointer() {
        let src = QttyQuantity::new(100.0, UnitId::Meter);
        let status =
            unsafe { qtty_quantity_convert(src, UnitId::Kilometer as u32, core::ptr::null_mut()) };
        assert_eq!(status, QttyStatus::NullOut);
    }

    #[test]
    fn test_invalid_unit_id_rejected() {
        let mut out = QttyQuantity::default();
        let src = QttyQuantity::new(100.0, UnitId::Meter);
        let status = unsafe { qtty_quantity_convert(src, 0, &mut out) };
        assert_eq!(status, QttyStatus::UnknownUnit);
    }

    #[test]
    fn test_unit_id_constants_match_enum_discriminants() {
        assert_eq!(QTTY_UNIT_METER, UnitId::Meter as u32);
        assert_eq!(QTTY_UNIT_KILOMETER, UnitId::Kilometer as u32);
        assert_eq!(QTTY_UNIT_SECOND, UnitId::Second as u32);
        assert_eq!(QTTY_UNIT_HOUR, UnitId::Hour as u32);
        assert_eq!(QTTY_UNIT_DAY, UnitId::Day as u32);
        assert_eq!(QTTY_UNIT_RADIAN, UnitId::Radian as u32);
        assert_eq!(QTTY_UNIT_DEGREE, UnitId::Degree as u32);
    }
}
