// SPDX-License-Identifier: BSD-3-Clause
// Copyright (C) 2026 Vallés Puig, Ramon

//! ABI-stable FFI types for `qtty` quantities.
//!
//! This module defines the `#[repr(C)]` and `#[repr(u32)]` types that form the stable C ABI
//! for cross-language interoperability. These types are designed to be safe to pass across
//! FFI boundaries.
//!
//! # ABI Stability Contract
//!
//! The discriminant values for [`UnitId`] and [`DimensionId`] are part of the ABI contract
//! and **MUST NEVER CHANGE** once assigned. New variants may be added with new discriminant
//! values, but existing values must remain stable across all versions.

use core::ffi::c_char;
use serde::{Deserialize, Serialize};

// =============================================================================
// Status Type
// =============================================================================

/// Status codes returned by every qtty-ffi function.
///
/// Callers must inspect this value before reading any output parameters.
///
/// # ABI Contract
///
/// Discriminant values are frozen; new variants may be added only at the end.
///
/// cbindgen:prefix-with-name
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QttyStatus {
    /// Operation completed successfully.
    Ok = 0,
    /// The provided unit ID is not recognized or valid.
    UnknownUnit = -1,
    /// Conversion requested between incompatible dimensions.
    IncompatibleDim = -2,
    /// A required output pointer was null.
    NullOut = -3,
    /// The provided output buffer is too small.
    BufferTooSmall = -4,
    /// A Rust panic was caught at the FFI boundary.
    ///
    /// This indicates a bug in the underlying library; the panic payload is
    /// discarded.  Domain errors (`UnknownUnit`, `IncompatibleDim`, etc.) are
    /// never reported via this variant.
    InternalPanic = -5,
}

impl From<QttyStatus> for i32 {
    #[inline]
    fn from(s: QttyStatus) -> i32 {
        s as i32
    }
}

// =============================================================================
// Format Flags (for qtty_quantity_format)
// =============================================================================

/// Format flag: default decimal notation (e.g. `"1234.57 m"`).
pub const QTTY_FMT_DEFAULT: u32 = 0;

/// Format flag: scientific notation with lowercase `e` (e.g. `"1.23e3 m"`).
pub const QTTY_FMT_LOWER_EXP: u32 = 1;

/// Format flag: scientific notation with uppercase `E` (e.g. `"1.23E3 m"`).
pub const QTTY_FMT_UPPER_EXP: u32 = 2;

// =============================================================================
// Dimension Identifiers
// =============================================================================

/// Dimension identifier for FFI.
///
/// Represents the physical dimension of a quantity. All discriminant values are
/// explicitly assigned and are part of the ABI contract.
///
/// # ABI Contract
///
/// **Discriminant values must never change.** New dimensions may be added with
/// new explicit discriminant values.
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DimensionId {
    /// Length dimension (e.g., meters, kilometers).
    Length = 1,
    /// Time dimension (e.g., seconds, hours).
    Time = 2,
    /// Angle dimension (e.g., radians, degrees).
    Angle = 3,
    /// Mass dimension (e.g., grams, kilograms).
    Mass = 4,
    /// Power dimension (e.g., watts, kilowatts).
    Power = 5,
    /// Area dimension (e.g., square metres, hectares).
    Area = 6,
    /// Volume dimension (e.g., cubic metres, litres).
    Volume = 7,
    /// Acceleration dimension (e.g., m/s², standard gravity).
    Acceleration = 8,
    /// Force dimension (e.g., newtons, kilonewtons).
    Force = 9,
    /// Energy dimension (e.g., joules, kilojoules).
    Energy = 10,
}

// =============================================================================
// Unit Identifiers
// =============================================================================

// =============================================================================
// Unit Identifiers
// =============================================================================

// The UnitId enum is generated by build.rs from qtty-core unit definitions.
// All discriminant values are explicitly assigned and are part of the ABI contract.
// Discriminant encoding: DSSCC where D=dimension (1 digit), SS=system (2 digits), CC=counter (2 digits)
// Units are grouped by dimension with ranges:
// - Length units: 1xxxx (10000-19999), Time units: 2xxxx (20000-29999), Angle units: 3xxxx (30000-39999)
// - Mass units: 4xxxx (40000-49999), Power units: 5xxxx (50000-59999)
include!(concat!(env!("OUT_DIR"), "/unit_id_enum.rs"));

impl UnitId {
    /// Returns the unit name as a static NUL-terminated C string.
    ///
    /// This is safe to call from C code and returns a pointer to static memory.
    #[inline]
    pub const fn name_cstr(&self) -> *const c_char {
        include!(concat!(env!("OUT_DIR"), "/unit_names_cstr.rs"))
    }

    /// Returns the unit name as a Rust string slice.
    #[inline]
    pub const fn name(&self) -> &'static str {
        include!(concat!(env!("OUT_DIR"), "/unit_names.rs"))
    }

    /// Returns the unit symbol as a Rust string slice (e.g., "m", "km", "s").
    #[inline]
    pub const fn symbol(&self) -> &'static str {
        include!(concat!(env!("OUT_DIR"), "/unit_symbols.rs"))
    }

    /// Attempts to create a `UnitId` from a raw `u32` discriminant value.
    ///
    /// Returns `None` if the value does not correspond to a valid unit.
    #[inline]
    pub const fn from_u32(value: u32) -> Option<Self> {
        include!(concat!(env!("OUT_DIR"), "/unit_from_u32.rs"))
    }
}

// =============================================================================
// Quantity Carrier Type
// =============================================================================

/// A POD quantity carrier type suitable for FFI.
///
/// This struct represents a physical quantity as a value paired with its unit.
/// It is `#[repr(C)]` to ensure a stable, predictable memory layout across
/// language boundaries.
///
/// # ABI Safety
///
/// The `unit` field is a raw `u32` rather than a [`UnitId`] enum so that C
/// callers can never construct a value with an invalid discriminant (which
/// would be instant UB in Rust).  Use [`unit_id()`](Self::unit_id) to
/// validate and decode the field on the Rust side.
///
/// # Memory Layout
///
/// - `value`: 8 bytes (f64)
/// - `unit`: 4 bytes (u32)
/// - Padding: 4 bytes (for alignment)
/// - Total: 16 bytes on most platforms
///
/// # Example
///
/// ```rust
/// use qtty_ffi::{QttyQuantity, UnitId};
///
/// let q = QttyQuantity {
///     value: 1000.0,
///     unit: UnitId::Meter as u32,
/// };
/// ```
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct QttyQuantity {
    /// The numeric value of the quantity.
    pub value: f64,
    /// Raw unit identifier.  Use [`unit_id()`](Self::unit_id) to validate.
    pub unit: u32,
}

impl QttyQuantity {
    /// Creates a new quantity from a validated [`UnitId`].
    #[inline]
    pub const fn new(value: f64, unit: UnitId) -> Self {
        Self {
            value,
            unit: unit as u32,
        }
    }

    /// Creates a new quantity from a raw `u32` unit identifier.
    ///
    /// This does **not** validate the unit ID.  Use [`unit_id()`](Self::unit_id)
    /// to check validity before relying on the value.
    #[inline]
    pub const fn from_raw(value: f64, unit: u32) -> Self {
        Self { value, unit }
    }

    /// Validates and returns the unit as a [`UnitId`].
    ///
    /// Returns `None` if the raw `unit` field does not correspond to a known
    /// unit.
    #[inline]
    pub fn unit_id(&self) -> Option<UnitId> {
        UnitId::from_u32(self.unit)
    }

    /// Checks if this quantity is compatible with another (same dimension).
    ///
    /// Returns `false` if either unit is invalid.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyQuantity, UnitId};
    ///
    /// let meters = QttyQuantity::new(100.0, UnitId::Meter);
    /// let km = QttyQuantity::new(1.0, UnitId::Kilometer);
    /// let seconds = QttyQuantity::new(60.0, UnitId::Second);
    ///
    /// assert!(meters.compatible(&km));
    /// assert!(!meters.compatible(&seconds));
    /// ```
    #[inline]
    pub fn compatible(&self, other: &Self) -> bool {
        match (self.unit_id(), other.unit_id()) {
            (Some(a), Some(b)) => crate::registry::compatible(a, b),
            _ => false,
        }
    }

    /// Returns the dimension of this quantity.
    ///
    /// Returns `None` if the unit is invalid.
    #[inline]
    pub fn dimension(&self) -> Option<DimensionId> {
        self.unit_id().and_then(crate::registry::dimension)
    }

    /// Converts this quantity to a different unit.
    ///
    /// Returns `None` if either unit is invalid or the units are incompatible.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyQuantity, UnitId};
    ///
    /// let meters = QttyQuantity::new(1000.0, UnitId::Meter);
    /// let km = meters.convert_to(UnitId::Kilometer).unwrap();
    /// assert!((km.value - 1.0).abs() < 1e-12);
    /// assert_eq!(km.unit, UnitId::Kilometer as u32);
    /// ```
    #[inline]
    pub fn convert_to(&self, target: UnitId) -> Option<Self> {
        let src = self.unit_id()?;
        crate::registry::convert_value(self.value, src, target)
            .ok()
            .map(|v| Self::new(v, target))
    }

    /// Adds two quantities, returning result in the left operand's unit.
    ///
    /// Returns `None` if either unit is invalid or the quantities have different
    /// dimensions.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyQuantity, UnitId};
    ///
    /// let a = QttyQuantity::new(1.0, UnitId::Kilometer);
    /// let b = QttyQuantity::new(500.0, UnitId::Meter);
    /// let sum = a.add(&b).unwrap();
    /// assert!((sum.value - 1.5).abs() < 1e-12);
    /// assert_eq!(sum.unit, UnitId::Kilometer as u32);
    /// ```
    #[inline]
    pub fn add(&self, other: &Self) -> Option<Self> {
        let self_unit = self.unit_id()?;
        let other_converted = other.convert_to(self_unit)?;
        Some(Self::new(self.value + other_converted.value, self_unit))
    }

    /// Subtracts another quantity from this one, returning result in this quantity's unit.
    ///
    /// Returns `None` if either unit is invalid or the quantities have different
    /// dimensions.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyQuantity, UnitId};
    ///
    /// let a = QttyQuantity::new(2.0, UnitId::Kilometer);
    /// let b = QttyQuantity::new(500.0, UnitId::Meter);
    /// let diff = a.sub(&b).unwrap();
    /// assert!((diff.value - 1.5).abs() < 1e-12);
    /// assert_eq!(diff.unit, UnitId::Kilometer as u32);
    /// ```
    #[inline]
    pub fn sub(&self, other: &Self) -> Option<Self> {
        let self_unit = self.unit_id()?;
        let other_converted = other.convert_to(self_unit)?;
        Some(Self::new(self.value - other_converted.value, self_unit))
    }

    /// Multiplies the quantity by a scalar value.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyQuantity, UnitId};
    ///
    /// let q = QttyQuantity::new(5.0, UnitId::Meter);
    /// let result = q.mul_scalar(3.0);
    /// assert!((result.value - 15.0).abs() < 1e-12);
    /// ```
    #[inline]
    pub const fn mul_scalar(&self, scalar: f64) -> Self {
        Self::from_raw(self.value * scalar, self.unit)
    }

    /// Divides the quantity by a scalar value.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyQuantity, UnitId};
    ///
    /// let q = QttyQuantity::new(15.0, UnitId::Meter);
    /// let result = q.div_scalar(3.0);
    /// assert!((result.value - 5.0).abs() < 1e-12);
    /// ```
    #[inline]
    pub const fn div_scalar(&self, scalar: f64) -> Self {
        Self::from_raw(self.value / scalar, self.unit)
    }

    /// Negates the quantity value.
    #[inline]
    pub const fn neg(&self) -> Self {
        Self::from_raw(-self.value, self.unit)
    }
}

impl Default for QttyQuantity {
    fn default() -> Self {
        Self {
            value: 0.0,
            unit: UnitId::Meter as u32,
        }
    }
}

// =============================================================================
// QttyDerivedQuantity - Compound quantities like velocity (m/s)
// =============================================================================

/// A derived quantity representing a compound unit (numerator/denominator).
///
/// This is useful for quantities like velocity (m/s), frequency (rad/s), etc.
///
/// # ABI Safety
///
/// Like [`QttyQuantity`], the unit fields are raw `u32` values to prevent UB
/// from invalid enum discriminants constructed by C callers.
///
/// # ABI Stability
///
/// This struct has `#[repr(C)]` layout:
/// - `value` at offset 0 (8 bytes)
/// - `numerator` at offset 8 (4 bytes)
/// - `denominator` at offset 12 (4 bytes)
/// - Total size: 16 bytes
///
/// # Example
///
/// ```rust
/// use qtty_ffi::{QttyDerivedQuantity, UnitId};
///
/// // Create a velocity: 100 m/s
/// let velocity = QttyDerivedQuantity::new(100.0, UnitId::Meter, UnitId::Second);
/// assert_eq!(velocity.value, 100.0);
/// assert_eq!(velocity.numerator, UnitId::Meter as u32);
/// assert_eq!(velocity.denominator, UnitId::Second as u32);
/// ```
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct QttyDerivedQuantity {
    /// The numeric value of the derived quantity.
    pub value: f64,
    /// Raw numerator unit identifier.
    pub numerator: u32,
    /// Raw denominator unit identifier.
    pub denominator: u32,
}

impl QttyDerivedQuantity {
    /// Creates a new derived quantity from validated [`UnitId`] values.
    #[inline]
    pub const fn new(value: f64, numerator: UnitId, denominator: UnitId) -> Self {
        Self {
            value,
            numerator: numerator as u32,
            denominator: denominator as u32,
        }
    }

    /// Creates a new derived quantity from raw `u32` unit identifiers.
    ///
    /// Does **not** validate the unit IDs.
    #[inline]
    pub const fn from_raw(value: f64, numerator: u32, denominator: u32) -> Self {
        Self {
            value,
            numerator,
            denominator,
        }
    }

    /// Validates and returns the numerator as a [`UnitId`].
    #[inline]
    pub fn numerator_id(&self) -> Option<UnitId> {
        UnitId::from_u32(self.numerator)
    }

    /// Validates and returns the denominator as a [`UnitId`].
    #[inline]
    pub fn denominator_id(&self) -> Option<UnitId> {
        UnitId::from_u32(self.denominator)
    }

    /// Returns the symbol string for this derived quantity (e.g., "m/s").
    ///
    /// Returns `None` if either unit ID is invalid.
    #[inline]
    pub fn symbol(&self) -> Option<String> {
        let num = self.numerator_id()?;
        let den = self.denominator_id()?;
        Some(format!("{}/{}", num.symbol(), den.symbol()))
    }

    /// Converts this derived quantity to different units.
    ///
    /// Returns `None` if any unit ID is invalid or the numerator/denominator
    /// dimensions are incompatible.
    ///
    /// # Example
    ///
    /// ```rust
    /// use qtty_ffi::{QttyDerivedQuantity, UnitId};
    ///
    /// // Convert 100 m/s to km/h
    /// let velocity = QttyDerivedQuantity::new(100.0, UnitId::Meter, UnitId::Second);
    /// let converted = velocity.convert_to(UnitId::Kilometer, UnitId::Hour).unwrap();
    /// // 100 m/s = 360 km/h
    /// assert!((converted.value - 360.0).abs() < 1e-9);
    /// ```
    pub fn convert_to(&self, target_num: UnitId, target_den: UnitId) -> Option<Self> {
        let src_num = self.numerator_id()?;
        let src_den = self.denominator_id()?;

        // Check dimensional compatibility
        let num_dim = crate::registry::dimension(src_num)?;
        let den_dim = crate::registry::dimension(src_den)?;
        let target_num_dim = crate::registry::dimension(target_num)?;
        let target_den_dim = crate::registry::dimension(target_den)?;

        if num_dim != target_num_dim || den_dim != target_den_dim {
            return None;
        }

        // Convert numerator: e.g., 100 m -> ? km
        let num_converted = crate::registry::convert_value(self.value, src_num, target_num).ok()?;

        // Convert denominator scale: e.g., 1 s -> ? h (0.000278 h)
        // If 1 s = 0.000278 h, then dividing by that gives us the factor
        let den_converted = crate::registry::convert_value(1.0, src_den, target_den).ok()?;

        // Guard against degenerate conversion factor.
        if den_converted == 0.0 || !den_converted.is_finite() {
            return None;
        }

        // Result = (num in new units) / (den scale factor)
        // 100 m = 0.1 km, 1 s = 1/3600 h
        // 100 m/s = 0.1 km / (1/3600 h) = 0.1 * 3600 km/h = 360 km/h
        let result_value = num_converted / den_converted;

        Some(Self::new(result_value, target_num, target_den))
    }

    /// Multiplies the derived quantity by a scalar.
    #[inline]
    pub const fn mul_scalar(&self, scalar: f64) -> Self {
        Self::from_raw(self.value * scalar, self.numerator, self.denominator)
    }

    /// Divides the derived quantity by a scalar.
    #[inline]
    pub const fn div_scalar(&self, scalar: f64) -> Self {
        Self::from_raw(self.value / scalar, self.numerator, self.denominator)
    }

    /// Negates the derived quantity.
    #[inline]
    pub const fn neg(&self) -> Self {
        Self::from_raw(-self.value, self.numerator, self.denominator)
    }
}

impl Default for QttyDerivedQuantity {
    fn default() -> Self {
        Self {
            value: 0.0,
            numerator: UnitId::Meter as u32,
            denominator: UnitId::Second as u32,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_id_discriminants_are_stable() {
        // These values are part of the ABI contract and must never change
        assert_eq!(UnitId::Meter as u32, 10011); // Length, SI, #11
        assert_eq!(UnitId::Kilometer as u32, 10014); // Length, SI, #14
        assert_eq!(UnitId::Second as u32, 20008); // Time, SI, #8
        assert_eq!(UnitId::Minute as u32, 21000); // Time, Common, #0
        assert_eq!(UnitId::Hour as u32, 21001); // Time, Common, #1
        assert_eq!(UnitId::Day as u32, 21002); // Time, Common, #2
        assert_eq!(UnitId::Radian as u32, 30001); // Angle, Radian, #1
        assert_eq!(UnitId::Degree as u32, 31004); // Angle, Degree, #4
    }

    #[test]
    fn dimension_id_discriminants_are_stable() {
        // These values are part of the ABI contract and must never change
        assert_eq!(DimensionId::Length as u32, 1);
        assert_eq!(DimensionId::Time as u32, 2);
        assert_eq!(DimensionId::Angle as u32, 3);
    }

    #[test]
    fn unit_id_from_u32_roundtrips() {
        for unit in [
            UnitId::Meter,
            UnitId::Kilometer,
            UnitId::Second,
            UnitId::Minute,
            UnitId::Hour,
            UnitId::Day,
            UnitId::Radian,
            UnitId::Degree,
        ] {
            let value = unit as u32;
            assert_eq!(UnitId::from_u32(value), Some(unit));
        }
    }

    #[test]
    fn unit_id_from_u32_rejects_invalid() {
        assert_eq!(UnitId::from_u32(0), None);
        assert_eq!(UnitId::from_u32(9999), None);
        // These ranges are unassigned as of the current discriminants.csv.
        // 80002+ (only 80000-80001 assigned for Acceleration)
        assert_eq!(UnitId::from_u32(80002), None);
        // 99999 is in Force range but unassigned (90000-92000 are used)
        assert_eq!(UnitId::from_u32(99999), None);
        assert_eq!(UnitId::from_u32(u32::MAX), None);
    }

    #[test]
    fn unit_names_are_not_empty() {
        for unit in [
            UnitId::Meter,
            UnitId::Kilometer,
            UnitId::Second,
            UnitId::Minute,
            UnitId::Hour,
            UnitId::Day,
            UnitId::Radian,
            UnitId::Degree,
        ] {
            assert!(!unit.name().is_empty());
        }
    }

    // ─── QttyQuantity method coverage ────────────────────────────────────────

    #[test]
    fn qtty_quantity_default() {
        let q = QttyQuantity::default();
        assert_eq!(q.value, 0.0);
        assert_eq!(q.unit, UnitId::Meter as u32);
    }

    #[test]
    fn qtty_quantity_unit_id() {
        let q = QttyQuantity::new(1.0, UnitId::Meter);
        assert_eq!(q.unit_id(), Some(UnitId::Meter));

        let bad = QttyQuantity::from_raw(1.0, 0);
        assert_eq!(bad.unit_id(), None);
    }

    #[test]
    fn qtty_quantity_neg() {
        let q = QttyQuantity::new(5.0, UnitId::Meter);
        let n = q.neg();
        assert_eq!(n.value, -5.0);
        assert_eq!(n.unit, UnitId::Meter as u32);
    }

    #[test]
    fn qtty_quantity_mul_scalar() {
        let q = QttyQuantity::new(4.0, UnitId::Kilometer);
        let r = q.mul_scalar(2.5);
        assert_eq!(r.value, 10.0);
        assert_eq!(r.unit, UnitId::Kilometer as u32);
    }

    #[test]
    fn qtty_quantity_div_scalar() {
        let q = QttyQuantity::new(15.0, UnitId::Second);
        let r = q.div_scalar(3.0);
        assert_eq!(r.value, 5.0);
        assert_eq!(r.unit, UnitId::Second as u32);
    }

    #[test]
    fn qtty_quantity_dimension() {
        let q = QttyQuantity::new(1.0, UnitId::Meter);
        assert_eq!(q.dimension(), Some(DimensionId::Length));

        let t = QttyQuantity::new(1.0, UnitId::Second);
        assert_eq!(t.dimension(), Some(DimensionId::Time));
    }

    #[test]
    fn qtty_quantity_dimension_invalid_returns_none() {
        let bad = QttyQuantity::from_raw(1.0, 0);
        assert_eq!(bad.dimension(), None);
    }

    #[test]
    fn qtty_quantity_compatible() {
        let a = QttyQuantity::new(1.0, UnitId::Meter);
        let b = QttyQuantity::new(1.0, UnitId::Kilometer);
        let c = QttyQuantity::new(1.0, UnitId::Second);

        assert!(a.compatible(&b));
        assert!(!a.compatible(&c));
    }

    #[test]
    fn qtty_quantity_compatible_invalid_returns_false() {
        let good = QttyQuantity::new(1.0, UnitId::Meter);
        let bad = QttyQuantity::from_raw(1.0, 0);
        assert!(!good.compatible(&bad));
        assert!(!bad.compatible(&good));
    }

    #[test]
    fn qtty_quantity_add_incompatible_returns_none() {
        let a = QttyQuantity::new(1.0, UnitId::Meter);
        let b = QttyQuantity::new(1.0, UnitId::Second);
        assert!(a.add(&b).is_none());
    }

    #[test]
    fn qtty_quantity_add_invalid_unit_returns_none() {
        let good = QttyQuantity::new(1.0, UnitId::Meter);
        let bad = QttyQuantity::from_raw(1.0, 0);
        assert!(good.add(&bad).is_none());
        assert!(bad.add(&good).is_none());
    }

    #[test]
    fn qtty_quantity_sub_incompatible_returns_none() {
        let a = QttyQuantity::new(1.0, UnitId::Meter);
        let b = QttyQuantity::new(1.0, UnitId::Second);
        assert!(a.sub(&b).is_none());
    }

    #[test]
    fn qtty_quantity_convert_to_invalid_src_returns_none() {
        let bad = QttyQuantity::from_raw(1.0, 0);
        assert!(bad.convert_to(UnitId::Meter).is_none());
    }

    // ─── QttyDerivedQuantity method coverage ─────────────────────────────────

    #[test]
    fn qtty_derived_quantity_default() {
        let d = QttyDerivedQuantity::default();
        assert_eq!(d.value, 0.0);
        assert_eq!(d.numerator, UnitId::Meter as u32);
        assert_eq!(d.denominator, UnitId::Second as u32);
    }

    #[test]
    fn qtty_derived_quantity_unit_id_accessors() {
        let d = QttyDerivedQuantity::new(1.0, UnitId::Meter, UnitId::Second);
        assert_eq!(d.numerator_id(), Some(UnitId::Meter));
        assert_eq!(d.denominator_id(), Some(UnitId::Second));

        let bad = QttyDerivedQuantity::from_raw(1.0, 0, 0);
        assert_eq!(bad.numerator_id(), None);
        assert_eq!(bad.denominator_id(), None);
    }

    #[test]
    fn qtty_derived_quantity_symbol() {
        let d = QttyDerivedQuantity::new(1.0, UnitId::Meter, UnitId::Second);
        let sym = d.symbol().expect("valid units should produce a symbol");
        // format is "numerator_symbol/denominator_symbol"
        assert!(sym.contains('/'), "symbol should contain '/'");
        assert!(!sym.is_empty());
        // Should look like "m/s"
        assert_eq!(
            sym,
            format!("{}/{}", UnitId::Meter.symbol(), UnitId::Second.symbol())
        );
    }

    #[test]
    fn qtty_derived_quantity_symbol_invalid_returns_none() {
        let bad = QttyDerivedQuantity::from_raw(1.0, 0, UnitId::Second as u32);
        assert!(bad.symbol().is_none());
    }

    #[test]
    fn qtty_derived_quantity_mul_scalar() {
        let d = QttyDerivedQuantity::new(10.0, UnitId::Meter, UnitId::Second);
        let r = d.mul_scalar(3.0);
        assert_eq!(r.value, 30.0);
        assert_eq!(r.numerator, UnitId::Meter as u32);
        assert_eq!(r.denominator, UnitId::Second as u32);
    }

    #[test]
    fn qtty_derived_quantity_div_scalar() {
        let d = QttyDerivedQuantity::new(30.0, UnitId::Kilometer, UnitId::Hour);
        let r = d.div_scalar(2.0);
        assert_eq!(r.value, 15.0);
        assert_eq!(r.numerator, UnitId::Kilometer as u32);
        assert_eq!(r.denominator, UnitId::Hour as u32);
    }

    #[test]
    fn qtty_derived_quantity_neg() {
        let d = QttyDerivedQuantity::new(5.0, UnitId::Meter, UnitId::Second);
        let n = d.neg();
        assert_eq!(n.value, -5.0);
        assert_eq!(n.numerator, UnitId::Meter as u32);
        assert_eq!(n.denominator, UnitId::Second as u32);
    }

    #[test]
    fn qtty_derived_quantity_convert_to_incompatible_returns_none() {
        // m/s → kg/h: numerator dimension mismatch
        let d = QttyDerivedQuantity::new(1.0, UnitId::Meter, UnitId::Second);
        assert!(d.convert_to(UnitId::Kilogram, UnitId::Hour).is_none());
    }

    #[test]
    fn qtty_derived_quantity_convert_to_invalid_src_returns_none() {
        let bad = QttyDerivedQuantity::from_raw(1.0, 0, UnitId::Second as u32);
        assert!(bad.convert_to(UnitId::Kilometer, UnitId::Hour).is_none());
    }

    #[test]
    fn qtty_quantity_serde_uses_raw_unit_ids() {
        let q = QttyQuantity::new(1.0, UnitId::Meter);
        let json = serde_json::to_string(&q).unwrap();
        assert_eq!(
            json,
            format!(r#"{{"value":1.0,"unit":{}}}"#, UnitId::Meter as u32)
        );

        let roundtrip: QttyQuantity = serde_json::from_str(&json).unwrap();
        assert_eq!(roundtrip, q);
    }

    #[test]
    fn qtty_derived_quantity_serde_uses_raw_unit_ids() {
        let q = QttyDerivedQuantity::new(2.0, UnitId::Meter, UnitId::Second);
        let json = serde_json::to_string(&q).unwrap();
        assert_eq!(
            json,
            format!(
                r#"{{"value":2.0,"numerator":{},"denominator":{}}}"#,
                UnitId::Meter as u32,
                UnitId::Second as u32
            )
        );

        let roundtrip: QttyDerivedQuantity = serde_json::from_str(&json).unwrap();
        assert_eq!(roundtrip, q);
    }
}
